### ISSUE TITLE
Arabiki64 ordering the gsSPVertex incorrectly in the exported displaylist

### ISSUE THREAD

**Issue by SuperGman04** [buu342/N64-Sausage64#40]
When I exported my model with arabiki64, I was very confused about why one of the gsSPVertex groups wasn't being lit correctly. After some poking around in the exported header, I found that it had incorrectly ordered the gsSPVertex to be before all of the rcp setup, like this:
```
    gsSPVertex(vtx_icosphere+0, 32, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 1, 0, 3, 0),
    ...
```
After reordering the display list to be like this:
```
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsDPPipeSync(),
    gsSPVertex(vtx_icosphere+0, 32, 0),
    gsSP2Triangles(0, 1, 2, 0, 1, 0, 3, 0),
    ...
```
Everything was being lit correctly.

**Comment by buu342** [comment]
That's an odd bug... Can you share the .S64 of the model so I can take a look at what happened there?

**Comment by SuperGman04** [comment]
Absolutely, here's the .S64:
[icospheretest.zip](https://github.com/buu342/N64-Sausage64/files/14859855/icospheretest.zip)

**Comment by buu342** [comment]
> Absolutely, here's the .S64: [icospheretest.zip](https://github.com/buu342/N64-Sausage64/files/14859855/icospheretest.zip) It's the default icosphere model from blender, with a material assigned and a bone added. 
Thank you!

> Slightly unrelated, but I was also having problems with the blender plugin. It seems like changing anything in the object settings, like the scale of the object, doesn't have any effect on the export.
That's normal, you need to apply your transforms (CTRL+A). I do have an issue to handle this in the tool though, since this is a common mistake https://github.com/buu342/N64-Sausage64/issues/36

**Comment by SuperGman04** [comment]
Ah, good to know for the future. Glad to see this is being improved, this is an invaluable tool! Without your stuff I wouldn't have been able to get this far with n64 homebrew so fast, so thank you!

**Comment by buu342** [comment]
Fixed in https://github.com/buu342/N64-Sausage64/commit/07d0f2aa9761a51db671718dd8b6ae0bc4dd0b2a
